{% set name = "here-location-services" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/here-location-services-{{ version }}.tar.gz
  sha256: 9be1ca7f4e7151774c889343f6cdbfb32301460fc992d141f33320e167a42e3b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - geojson
    - python >=3.6
    - requests
    - flexpolyline
    - pandas

test:
  imports:
    - here_location_services
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://here.com
  summary: HERE Location Services for Python
  dev_url: https://github.com/heremaps/here-location-services-python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sackh
